name: Example
on: 
  push:

jobs:
  export:
    name: Export Job
    runs-on: ["Linux"]
    steps:
      - name: Step
        run: echo Hi

  build:
    name: Build Job
    needs: export
    runs-on: ["Linux"]
    steps:
      - name: Step
        run: echo Hi
